language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cp dplace/settings.travis dplace/settings.py
# command to run tests
script: "python manage.py test"